### PR TITLE
Introduce Gush Workflows monitoring

### PR DESCRIPTION
**Pull request by cabello**
Uses Sidekiq Web infra-structure to display & monitor Gush Workflows.

**Note**: This may not be production ready yet because it loads all Gush workflows keys from the Redis database.

image

### CODE REVIEW

**Comment by pokonski** [comment]
This is pretty cool! I didn't know you can extend the Web UI so easily, will have a look :)

**Comment by cabello** [comment]
Hello, any changes I can do to make this PR viable?

**Comment by pokonski** [comment]
Hi Danillo!

I definitely want to have this merged but was swamped but work so didn't
have time to review this.
I'll have a deeper look this weekend!

Thanks for this :)

17 paź 2016 9:57 PM "Danilo Cabello" <notifications@github.com> napisał(a):

**Comment by ferusinfo** [comment]
Is there any chance you could squash the commits? It would be easier to read it - I might find time this week to look through it ;)

**Comment by cabello** [comment]
HI, I am closing this PR due to lack of traction, I understand everyone is busy with something else. Please feel free to use my contribution if you think it's useful.

**Comment by dmitrypol** [comment]
this would be a great feature to add

**Pull request closed without merging**
