### PR TITLE
Update: thor to >= 0.19, < 1.3; terminal-table to >= 1.4, < 3.1

### PR DESCRIPTION
**Pull request by joshRpowell**
- https://github.com/rails/thor/releases
- https://github.com/tj/terminal-table/releases

### CODE REVIEW

**Comment by shaul75** [comment]
Thanks @pokonski and @joshRpowell,
Any ETA for merging this?

**Comment by andreavocado** [comment]
Please merge and release a new version as this blocks an upgrade to rails 6.1 of my application

**Review by andreavocado — APPROVED** [review]

**Comment by sullyvannunes** [comment]
Hey, everyone. Hope you all are doing well. Is there an ETA for merging this?

**Comment by pokonski** [comment]
Hey @joshRpowell! Massive delay on my end, apologies. Since it's been stuck for a while, maybe we can or should bump this to a newer version of thor. If there is one?

**Comment by joshRpowell** [comment]
> Hey @joshRpowell! Massive delay on my end, apologies. Since it's been stuck for a while, maybe we can or should bump this to a newer version of thor. If there is one?

@pokonski thanks for the check-in. Agree. There have been some updates. I've updated the links in the description. I'll push a commit with the changes.

**Comment by joshRpowell** [comment]
@pokonski let me know if you'll squash and merge, or if you need me to squash in advance.

**Comment by pokonski** [comment]
I'll squash and merge, no need to do it manually :)

pt., 16 wrz 2022, 19:16 użytkownik Josh Powell ***@***.***>
napisał:

**Pull request merged**
