### PR TITLE
[1.0] ActiveJob rewrite

### PR DESCRIPTION
**Pull request by pokonski**

### CODE REVIEW

**Comment by matti** [comment]
@pokonski what’s the status? I’d love to see this merged

**Comment by pokonski** [comment]
Hey @matti, I'd be grateful for you to be a tester of this branch :) I could use more users trying this out.

**Comment by matti** [comment]
@aom highly recommended

**Comment by pokonski** [comment]
@matti @aom This is now released under 1.0.0 in Rubygems, see the updated README on master for new instructions on how to get started :)

**Comment by ferusinfo** [comment]
Can you create a doc saying what steps we should take to go trough migration process from versions lower than 1.0.0?

**Comment by pokonski** [comment]
@ferusinfo sure, I'll prepare a doc and link it here :) But a short version until then:

1. rename `def work` to `def perform` in your jobs
2. if you used `bundle exec gush work` to start background jobs,  you now have to start the backend directly (for example `bundle exec sidekiq -q gush` or for Que: `bundle exec que` etc.


Other than that there were no changes to DSL.

**Pull request merged**
