### PR TITLE
Add Rails version to CI matrix

### PR DESCRIPTION
**Pull request by kzkn**
Add Rails version to CI matrix. The versions of rails in matrix, the supported major versions by gush currently.

### CODE REVIEW

**Comment by joshRpowell** [comment]
@kzkn with this merged, would you mind adding Rails 7.0 to the matrix?

**Comment by pokonski** [comment]
@joshRpowell I can do it straight on master after merging :+1:

**Comment by kzkn** [comment]
Thanks for the merge.
Looking forward to getting gush working with Rails 7.0 as well :smile:

**Comment by kzkn** [comment]
It had been already released a new version with Rails 7.0 support! :tada:

**Pull request merged**
